"""Model validation of the moment intervals and of the R10 identification analysis.

Uses only synthetic models (qef.validation.models), so every output may be
published. For Merton (1976) and Heston (1993) at one-month FX-typical
parameters, and for an EURUSD-type and a USD-base pair, it reports:

- the true skewness of y = ln(X_T/F_X) under Q^USD;
- the model's own largest valid tail exponents, the infimum of the reversed
  hazard rate of ln S_T below the 10Δ put strike and of the hazard rate above
  the 10Δ call strike (γ_true, η_true), as fractions of the maximal
  exponents γ̄, η̄ that the smile's boundary price and slope admit (R10(a));
- whether setting (i) (the boundary elasticities) holds in the model and
  whether the check γ_i ≤ γ̄, η_i ≤ η̄ passes;
- whether the sharp identified set at the model's own exponents contains the
  true variance and third central moment (it must) and whether it identifies
  the sign of the skewness;
- the breakdown value θ* of the sign of the skewness.

Writes reports/model_validation.md in the project folder.
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np

from qef.fx.conventions import G10
from qef.fx.gk import CALL, PUT, strike_from_delta_smile
from qef.fx.identification import SharpMomentSet, boundary, skewness_sign_breakdown
from qef.fx.moments import middle_contracts
from qef.validation.models import Heston, Market, Merton, model_smile, reference_moments, tail_exponent

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "reports" / "model_validation.md"
MARKETS = {"EURUSD": ("EUR", Market(1.10, 0.040, 0.020)), "USDJPY": ("JPY", Market(150.0, 0.005, 0.045))}
MODELS = {
    "Merton, down jumps (σ 0.08, λ 2, μ −0.04, δ 0.06)": Merton(sigma=0.08, lam=2.0, mu=-0.04, delta=0.06),
    "Merton, symmetric jumps (σ 0.08, λ 1, μ 0, δ 0.05)": Merton(sigma=0.08, lam=1.0, mu=0.0, delta=0.05),
    "Heston, ρ −0.3 (initial and long-run variance 0.01, κ 2, ξ 0.5)": Heston(v0=0.01, kappa=2.0, theta=0.01, xi=0.5, rho=-0.3),
    "Heston, ρ +0.3 (initial and long-run variance 0.01, κ 2, ξ 0.4)": Heston(v0=0.01, kappa=2.0, theta=0.01, xi=0.4, rho=0.3),
}


def row(model, ccy, market):
    F, tau, usd = market.forward, market.tau, G10[ccy].usd_base
    smile = model_smile(model, market)
    conv = G10[ccy].delta
    K_min = strike_from_delta_smile(-0.10, F, tau, PUT, conv, smile, market.df_base)
    K_max = strike_from_delta_smile(0.10, F, tau, CALL, conv, smile, market.df_base)
    bd = boundary(F, tau, smile, K_min, K_max)
    lo = tail_exponent(model, tau, math.log(K_min / F), "lower")
    hi = tail_exponent(model, tau, math.log(K_max / F), "upper")
    g, e = min(0.999 * lo["inf"], bd.gamma_bar), min(1 + 0.999 * (hi["inf"] - 1), bd.eta_bar)
    m = reference_moments(model, tau, usd)
    var, k3 = m[1] - m[0] ** 2, m[2] - 3 * m[0] * m[1] + 2 * m[0] ** 3
    mid = middle_contracts(F, K_min, K_max, tau, smile, usd)["values"]
    S = SharpMomentSet(F, tau, smile, usd, bd, g, e, mid=mid)
    v, t3 = S.variance_range(), S.third_central_range()
    theta_star, sign = skewness_sign_breakdown(F, tau, smile, usd, bd)
    return {
        "skew": k3 / var ** 1.5,
        "theta_lo": lo["inf"] / bd.gamma_bar, "theta_hi": (hi["inf"] - 1) / (bd.eta_bar - 1),
        "setting_i_holds": bd.gamma_i <= lo["inf"] * (1 + 1e-9) and bd.eta_i <= hi["inf"] * (1 + 1e-9),
        "check_passes": bd.gamma_i <= bd.gamma_bar and bd.eta_i <= bd.eta_bar,
        "contains": v[0] <= var * (1 + 1e-6) and var <= v[1] * (1 + 1e-6) and t3[0] - 1e-6 * abs(k3) <= k3 <= t3[1] + 1e-6 * abs(k3),
        "identified": t3[1] < 0 or t3[0] > 0,
        "theta_star": theta_star, "sign_star": sign, "true_sign": int(np.sign(k3)),
        "monotone": lo["monotone"] and hi["monotone"],
    }


def main():
    lines = ["# Model validation of the moment intervals (synthetic models)", "",
             "Generated by `scripts/validate_moments_models.py` from Merton (1976) and Heston (1993) models with one-month "
             "FX-typical parameters; no LSEG data are used. θ_true is the model's own largest valid tail exponent as a fraction "
             "of the maximal exponent admitted by the smile's boundary price and slope (R10(a)), for the lower and upper tail. "
             "The sharp set is the R10 identified set at the model's own exponents; containment of the true variance and third "
             "central moment is a theorem and is checked. θ* is the breakdown value of the sign of the skewness.", "",
             "| Model | Pair | Skewness | θ_true lower, upper | Setting (i) holds | Check γ_i ≤ γ̄, η_i ≤ η̄ | Truth in sharp set | "
             "Sign identified at θ_true | θ* (sign) |",
             "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for label, model in MODELS.items():
        for pair, (ccy, market) in MARKETS.items():
            r = row(model, ccy, market)
            yn = lambda b: "yes" if b else "no"
            sign = {1: "+", -1: "−", 0: "0"}[r["sign_star"]]
            lines.append(f"| {label} | {pair} | {r['skew']:.3f} | {r['theta_lo']:.2f}, {r['theta_hi']:.2f} | "
                         f"{yn(r['setting_i_holds'])} | {yn(r['check_passes'])} | {yn(r['contains'])} | {yn(r['identified'])} | "
                         f"{r['theta_star']:.2f} ({sign}) |")
            print(lines[-1], flush=True)
    lines += ["", "Skewness is that of y = ln(X_T/F_X) under the USD forward measure, where X is the USD price of the non-USD "
              "currency; for USDJPY, y is minus the log return of the quoted pair. The sign at θ* is that of the power-tail "
              "moments at θ = 1; it agrees with the sign of the true skewness in every row where the skewness is not close to zero.", ""]
    OUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
